# Site settings
title: 
email: hello@qichenzhang.com
description: > # this means to ignore newlines until "baseurl:"
  Do you want to give me money?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qichenzhang.com" # the base hostname & protocol for your site
twitter_username: qichenzhang
github_username:  qichenz

# Build settings
markdown: kramdown